[theme]
base = "light"
primaryColor = "#D9728E"
backgroundColor = "#FFF9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#3D2F35"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false